services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: comerzia_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: ComerziaDBPUCPGrupo03
    ports:
      - "3306:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql

# volumes:
#   mysql_data:
