//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPubWA.ServicioWeb {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.eventmastersoft.pucp.edu.pe", ConfigurationName="ServicioWeb.RecursosHumanosWS")]
    public interface RecursosHumanosWS {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.eventmastersoft.pucp.edu.pe/RecursosHumanosWS/devolverNombreEmple" +
            "adoRequest", ReplyAction="http://services.eventmastersoft.pucp.edu.pe/RecursosHumanosWS/devolverNombreEmple" +
            "adoResponse")]
        SoftPubWA.ServicioWeb.devolverNombreEmpleadoResponse devolverNombreEmpleado(SoftPubWA.ServicioWeb.devolverNombreEmpleadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.eventmastersoft.pucp.edu.pe/RecursosHumanosWS/devolverNombreEmple" +
            "adoRequest", ReplyAction="http://services.eventmastersoft.pucp.edu.pe/RecursosHumanosWS/devolverNombreEmple" +
            "adoResponse")]
        System.Threading.Tasks.Task<SoftPubWA.ServicioWeb.devolverNombreEmpleadoResponse> devolverNombreEmpleadoAsync(SoftPubWA.ServicioWeb.devolverNombreEmpleadoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cuenta del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.eventmastersoft.pucp.edu.pe/RecursosHumanosWS/verEmpleadoRequest", ReplyAction="http://services.eventmastersoft.pucp.edu.pe/RecursosHumanosWS/verEmpleadoResponse" +
            "")]
        SoftPubWA.ServicioWeb.verEmpleadoResponse verEmpleado(SoftPubWA.ServicioWeb.verEmpleadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.eventmastersoft.pucp.edu.pe/RecursosHumanosWS/verEmpleadoRequest", ReplyAction="http://services.eventmastersoft.pucp.edu.pe/RecursosHumanosWS/verEmpleadoResponse" +
            "")]
        System.Threading.Tasks.Task<SoftPubWA.ServicioWeb.verEmpleadoResponse> verEmpleadoAsync(SoftPubWA.ServicioWeb.verEmpleadoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class devolverNombreEmpleadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="devolverNombreEmpleado", Namespace="http://services.eventmastersoft.pucp.edu.pe", Order=0)]
        public SoftPubWA.ServicioWeb.devolverNombreEmpleadoRequestBody Body;
        
        public devolverNombreEmpleadoRequest() {
        }
        
        public devolverNombreEmpleadoRequest(SoftPubWA.ServicioWeb.devolverNombreEmpleadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class devolverNombreEmpleadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idEmpleado;
        
        public devolverNombreEmpleadoRequestBody() {
        }
        
        public devolverNombreEmpleadoRequestBody(int idEmpleado) {
            this.idEmpleado = idEmpleado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class devolverNombreEmpleadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="devolverNombreEmpleadoResponse", Namespace="http://services.eventmastersoft.pucp.edu.pe", Order=0)]
        public SoftPubWA.ServicioWeb.devolverNombreEmpleadoResponseBody Body;
        
        public devolverNombreEmpleadoResponse() {
        }
        
        public devolverNombreEmpleadoResponse(SoftPubWA.ServicioWeb.devolverNombreEmpleadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class devolverNombreEmpleadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public devolverNombreEmpleadoResponseBody() {
        }
        
        public devolverNombreEmpleadoResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verEmpleadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="verEmpleado", Namespace="http://services.eventmastersoft.pucp.edu.pe", Order=0)]
        public SoftPubWA.ServicioWeb.verEmpleadoRequestBody Body;
        
        public verEmpleadoRequest() {
        }
        
        public verEmpleadoRequest(SoftPubWA.ServicioWeb.verEmpleadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class verEmpleadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cuenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contrasenha;
        
        public verEmpleadoRequestBody() {
        }
        
        public verEmpleadoRequestBody(string cuenta, string contrasenha) {
            this.cuenta = cuenta;
            this.contrasenha = contrasenha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verEmpleadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="verEmpleadoResponse", Namespace="http://services.eventmastersoft.pucp.edu.pe", Order=0)]
        public SoftPubWA.ServicioWeb.verEmpleadoResponseBody Body;
        
        public verEmpleadoResponse() {
        }
        
        public verEmpleadoResponse(SoftPubWA.ServicioWeb.verEmpleadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class verEmpleadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        public verEmpleadoResponseBody() {
        }
        
        public verEmpleadoResponseBody(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RecursosHumanosWSChannel : SoftPubWA.ServicioWeb.RecursosHumanosWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecursosHumanosWSClient : System.ServiceModel.ClientBase<SoftPubWA.ServicioWeb.RecursosHumanosWS>, SoftPubWA.ServicioWeb.RecursosHumanosWS {
        
        public RecursosHumanosWSClient() {
        }
        
        public RecursosHumanosWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecursosHumanosWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecursosHumanosWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecursosHumanosWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPubWA.ServicioWeb.devolverNombreEmpleadoResponse SoftPubWA.ServicioWeb.RecursosHumanosWS.devolverNombreEmpleado(SoftPubWA.ServicioWeb.devolverNombreEmpleadoRequest request) {
            return base.Channel.devolverNombreEmpleado(request);
        }
        
        public string devolverNombreEmpleado(int idEmpleado) {
            SoftPubWA.ServicioWeb.devolverNombreEmpleadoRequest inValue = new SoftPubWA.ServicioWeb.devolverNombreEmpleadoRequest();
            inValue.Body = new SoftPubWA.ServicioWeb.devolverNombreEmpleadoRequestBody();
            inValue.Body.idEmpleado = idEmpleado;
            SoftPubWA.ServicioWeb.devolverNombreEmpleadoResponse retVal = ((SoftPubWA.ServicioWeb.RecursosHumanosWS)(this)).devolverNombreEmpleado(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPubWA.ServicioWeb.devolverNombreEmpleadoResponse> SoftPubWA.ServicioWeb.RecursosHumanosWS.devolverNombreEmpleadoAsync(SoftPubWA.ServicioWeb.devolverNombreEmpleadoRequest request) {
            return base.Channel.devolverNombreEmpleadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPubWA.ServicioWeb.devolverNombreEmpleadoResponse> devolverNombreEmpleadoAsync(int idEmpleado) {
            SoftPubWA.ServicioWeb.devolverNombreEmpleadoRequest inValue = new SoftPubWA.ServicioWeb.devolverNombreEmpleadoRequest();
            inValue.Body = new SoftPubWA.ServicioWeb.devolverNombreEmpleadoRequestBody();
            inValue.Body.idEmpleado = idEmpleado;
            return ((SoftPubWA.ServicioWeb.RecursosHumanosWS)(this)).devolverNombreEmpleadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPubWA.ServicioWeb.verEmpleadoResponse SoftPubWA.ServicioWeb.RecursosHumanosWS.verEmpleado(SoftPubWA.ServicioWeb.verEmpleadoRequest request) {
            return base.Channel.verEmpleado(request);
        }
        
        public int verEmpleado(string cuenta, string contrasenha) {
            SoftPubWA.ServicioWeb.verEmpleadoRequest inValue = new SoftPubWA.ServicioWeb.verEmpleadoRequest();
            inValue.Body = new SoftPubWA.ServicioWeb.verEmpleadoRequestBody();
            inValue.Body.cuenta = cuenta;
            inValue.Body.contrasenha = contrasenha;
            SoftPubWA.ServicioWeb.verEmpleadoResponse retVal = ((SoftPubWA.ServicioWeb.RecursosHumanosWS)(this)).verEmpleado(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPubWA.ServicioWeb.verEmpleadoResponse> SoftPubWA.ServicioWeb.RecursosHumanosWS.verEmpleadoAsync(SoftPubWA.ServicioWeb.verEmpleadoRequest request) {
            return base.Channel.verEmpleadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPubWA.ServicioWeb.verEmpleadoResponse> verEmpleadoAsync(string cuenta, string contrasenha) {
            SoftPubWA.ServicioWeb.verEmpleadoRequest inValue = new SoftPubWA.ServicioWeb.verEmpleadoRequest();
            inValue.Body = new SoftPubWA.ServicioWeb.verEmpleadoRequestBody();
            inValue.Body.cuenta = cuenta;
            inValue.Body.contrasenha = contrasenha;
            return ((SoftPubWA.ServicioWeb.RecursosHumanosWS)(this)).verEmpleadoAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.comerziasoft.pucp.edu.pe", ConfigurationName="ServicioWeb.AlmacenWS")]
    public interface AlmacenWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.comerziasoft.pucp.edu.pe/AlmacenWS/insertarProductoAlmacenadoRequ" +
            "est", ReplyAction="http://services.comerziasoft.pucp.edu.pe/AlmacenWS/insertarProductoAlmacenadoResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPubWA.ServicioWeb.insertarProductoAlmacenadoResponse insertarProductoAlmacenado(SoftPubWA.ServicioWeb.insertarProductoAlmacenadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.comerziasoft.pucp.edu.pe/AlmacenWS/insertarProductoAlmacenadoRequ" +
            "est", ReplyAction="http://services.comerziasoft.pucp.edu.pe/AlmacenWS/insertarProductoAlmacenadoResp" +
            "onse")]
        System.Threading.Tasks.Task<SoftPubWA.ServicioWeb.insertarProductoAlmacenadoResponse> insertarProductoAlmacenadoAsync(SoftPubWA.ServicioWeb.insertarProductoAlmacenadoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.comerziasoft.pucp.edu.pe/AlmacenWS/listarAlmacenesRequest", ReplyAction="http://services.comerziasoft.pucp.edu.pe/AlmacenWS/listarAlmacenesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPubWA.ServicioWeb.listarAlmacenesResponse listarAlmacenes(SoftPubWA.ServicioWeb.listarAlmacenesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.comerziasoft.pucp.edu.pe/AlmacenWS/listarAlmacenesRequest", ReplyAction="http://services.comerziasoft.pucp.edu.pe/AlmacenWS/listarAlmacenesResponse")]
        System.Threading.Tasks.Task<SoftPubWA.ServicioWeb.listarAlmacenesResponse> listarAlmacenesAsync(SoftPubWA.ServicioWeb.listarAlmacenesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.comerziasoft.pucp.edu.pe/AlmacenWS/buscarProductoPorIdRequest", ReplyAction="http://services.comerziasoft.pucp.edu.pe/AlmacenWS/buscarProductoPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPubWA.ServicioWeb.buscarProductoPorIdResponse buscarProductoPorId(SoftPubWA.ServicioWeb.buscarProductoPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.comerziasoft.pucp.edu.pe/AlmacenWS/buscarProductoPorIdRequest", ReplyAction="http://services.comerziasoft.pucp.edu.pe/AlmacenWS/buscarProductoPorIdResponse")]
        System.Threading.Tasks.Task<SoftPubWA.ServicioWeb.buscarProductoPorIdResponse> buscarProductoPorIdAsync(SoftPubWA.ServicioWeb.buscarProductoPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.comerziasoft.pucp.edu.pe/AlmacenWS/listarPorAlmacenRequest", ReplyAction="http://services.comerziasoft.pucp.edu.pe/AlmacenWS/listarPorAlmacenResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPubWA.ServicioWeb.listarPorAlmacenResponse listarPorAlmacen(SoftPubWA.ServicioWeb.listarPorAlmacenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.comerziasoft.pucp.edu.pe/AlmacenWS/listarPorAlmacenRequest", ReplyAction="http://services.comerziasoft.pucp.edu.pe/AlmacenWS/listarPorAlmacenResponse")]
        System.Threading.Tasks.Task<SoftPubWA.ServicioWeb.listarPorAlmacenResponse> listarPorAlmacenAsync(SoftPubWA.ServicioWeb.listarPorAlmacenRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.comerziasoft.pucp.edu.pe/AlmacenWS/buscarPorNombreRequest", ReplyAction="http://services.comerziasoft.pucp.edu.pe/AlmacenWS/buscarPorNombreResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPubWA.ServicioWeb.buscarPorNombreResponse buscarPorNombre(SoftPubWA.ServicioWeb.buscarPorNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.comerziasoft.pucp.edu.pe/AlmacenWS/buscarPorNombreRequest", ReplyAction="http://services.comerziasoft.pucp.edu.pe/AlmacenWS/buscarPorNombreResponse")]
        System.Threading.Tasks.Task<SoftPubWA.ServicioWeb.buscarPorNombreResponse> buscarPorNombreAsync(SoftPubWA.ServicioWeb.buscarPorNombreRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.comerziasoft.pucp.edu.pe/AlmacenWS/obtenerPorIdRequest", ReplyAction="http://services.comerziasoft.pucp.edu.pe/AlmacenWS/obtenerPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPubWA.ServicioWeb.obtenerPorIdResponse obtenerPorId(SoftPubWA.ServicioWeb.obtenerPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.comerziasoft.pucp.edu.pe/AlmacenWS/obtenerPorIdRequest", ReplyAction="http://services.comerziasoft.pucp.edu.pe/AlmacenWS/obtenerPorIdResponse")]
        System.Threading.Tasks.Task<SoftPubWA.ServicioWeb.obtenerPorIdResponse> obtenerPorIdAsync(SoftPubWA.ServicioWeb.obtenerPorIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarProductoAlmacenado", WrapperNamespace="http://services.comerziasoft.pucp.edu.pe", IsWrapped=true)]
    public partial class insertarProductoAlmacenadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.comerziasoft.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idAlmacen;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.comerziasoft.pucp.edu.pe", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaAlmacenado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.comerziasoft.pucp.edu.pe", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int stock;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.comerziasoft.pucp.edu.pe", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idProd;
        
        public insertarProductoAlmacenadoRequest() {
        }
        
        public insertarProductoAlmacenadoRequest(int idAlmacen, System.DateTime fechaAlmacenado, int stock, int idProd) {
            this.idAlmacen = idAlmacen;
            this.fechaAlmacenado = fechaAlmacenado;
            this.stock = stock;
            this.idProd = idProd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarProductoAlmacenadoResponse", WrapperNamespace="http://services.comerziasoft.pucp.edu.pe", IsWrapped=true)]
    public partial class insertarProductoAlmacenadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.comerziasoft.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarProductoAlmacenadoResponse() {
        }
        
        public insertarProductoAlmacenadoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.comerziasoft.pucp.edu.pe")]
    public partial class almacen : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private string estadoField;
        
        private int idAlmacenField;
        
        private bool idAlmacenFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idAlmacen {
            get {
                return this.idAlmacenField;
            }
            set {
                this.idAlmacenField = value;
                this.RaisePropertyChanged("idAlmacen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idAlmacenSpecified {
            get {
                return this.idAlmacenFieldSpecified;
            }
            set {
                this.idAlmacenFieldSpecified = value;
                this.RaisePropertyChanged("idAlmacenSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.comerziasoft.pucp.edu.pe")]
    public partial class productoAlmacenado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fechaAlmacenadoField;
        
        private bool fechaAlmacenadoFieldSpecified;
        
        private int idAlmacenField;
        
        private bool idAlmacenFieldSpecified;
        
        private int idProductoField;
        
        private bool idProductoFieldSpecified;
        
        private int idProductoAlmacenadoField;
        
        private bool idProductoAlmacenadoFieldSpecified;
        
        private int stockActualField;
        
        private bool stockActualFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fechaAlmacenado {
            get {
                return this.fechaAlmacenadoField;
            }
            set {
                this.fechaAlmacenadoField = value;
                this.RaisePropertyChanged("fechaAlmacenado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaAlmacenadoSpecified {
            get {
                return this.fechaAlmacenadoFieldSpecified;
            }
            set {
                this.fechaAlmacenadoFieldSpecified = value;
                this.RaisePropertyChanged("fechaAlmacenadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idAlmacen {
            get {
                return this.idAlmacenField;
            }
            set {
                this.idAlmacenField = value;
                this.RaisePropertyChanged("idAlmacen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idAlmacenSpecified {
            get {
                return this.idAlmacenFieldSpecified;
            }
            set {
                this.idAlmacenFieldSpecified = value;
                this.RaisePropertyChanged("idAlmacenSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idProducto {
            get {
                return this.idProductoField;
            }
            set {
                this.idProductoField = value;
                this.RaisePropertyChanged("idProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProductoSpecified {
            get {
                return this.idProductoFieldSpecified;
            }
            set {
                this.idProductoFieldSpecified = value;
                this.RaisePropertyChanged("idProductoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idProductoAlmacenado {
            get {
                return this.idProductoAlmacenadoField;
            }
            set {
                this.idProductoAlmacenadoField = value;
                this.RaisePropertyChanged("idProductoAlmacenado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProductoAlmacenadoSpecified {
            get {
                return this.idProductoAlmacenadoFieldSpecified;
            }
            set {
                this.idProductoAlmacenadoFieldSpecified = value;
                this.RaisePropertyChanged("idProductoAlmacenadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int stockActual {
            get {
                return this.stockActualField;
            }
            set {
                this.stockActualField = value;
                this.RaisePropertyChanged("stockActual");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stockActualSpecified {
            get {
                return this.stockActualFieldSpecified;
            }
            set {
                this.stockActualFieldSpecified = value;
                this.RaisePropertyChanged("stockActualSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.comerziasoft.pucp.edu.pe")]
    public partial class producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idProductoField;
        
        private bool idProductoFieldSpecified;
        
        private string nombreProductoField;
        
        private double precioField;
        
        private bool precioFieldSpecified;
        
        private int stockMinimoField;
        
        private bool stockMinimoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idProducto {
            get {
                return this.idProductoField;
            }
            set {
                this.idProductoField = value;
                this.RaisePropertyChanged("idProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProductoSpecified {
            get {
                return this.idProductoFieldSpecified;
            }
            set {
                this.idProductoFieldSpecified = value;
                this.RaisePropertyChanged("idProductoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombreProducto {
            get {
                return this.nombreProductoField;
            }
            set {
                this.nombreProductoField = value;
                this.RaisePropertyChanged("nombreProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool precioSpecified {
            get {
                return this.precioFieldSpecified;
            }
            set {
                this.precioFieldSpecified = value;
                this.RaisePropertyChanged("precioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int stockMinimo {
            get {
                return this.stockMinimoField;
            }
            set {
                this.stockMinimoField = value;
                this.RaisePropertyChanged("stockMinimo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stockMinimoSpecified {
            get {
                return this.stockMinimoFieldSpecified;
            }
            set {
                this.stockMinimoFieldSpecified = value;
                this.RaisePropertyChanged("stockMinimoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAlmacenes", WrapperNamespace="http://services.comerziasoft.pucp.edu.pe", IsWrapped=true)]
    public partial class listarAlmacenesRequest {
        
        public listarAlmacenesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAlmacenesResponse", WrapperNamespace="http://services.comerziasoft.pucp.edu.pe", IsWrapped=true)]
    public partial class listarAlmacenesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.comerziasoft.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPubWA.ServicioWeb.almacen[] @return;
        
        public listarAlmacenesResponse() {
        }
        
        public listarAlmacenesResponse(SoftPubWA.ServicioWeb.almacen[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarProductoPorId", WrapperNamespace="http://services.comerziasoft.pucp.edu.pe", IsWrapped=true)]
    public partial class buscarProductoPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.comerziasoft.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idProd;
        
        public buscarProductoPorIdRequest() {
        }
        
        public buscarProductoPorIdRequest(int idProd) {
            this.idProd = idProd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarProductoPorIdResponse", WrapperNamespace="http://services.comerziasoft.pucp.edu.pe", IsWrapped=true)]
    public partial class buscarProductoPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.comerziasoft.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPubWA.ServicioWeb.producto @return;
        
        public buscarProductoPorIdResponse() {
        }
        
        public buscarProductoPorIdResponse(SoftPubWA.ServicioWeb.producto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorAlmacen", WrapperNamespace="http://services.comerziasoft.pucp.edu.pe", IsWrapped=true)]
    public partial class listarPorAlmacenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.comerziasoft.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idAlmacen;
        
        public listarPorAlmacenRequest() {
        }
        
        public listarPorAlmacenRequest(string idAlmacen) {
            this.idAlmacen = idAlmacen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorAlmacenResponse", WrapperNamespace="http://services.comerziasoft.pucp.edu.pe", IsWrapped=true)]
    public partial class listarPorAlmacenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.comerziasoft.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPubWA.ServicioWeb.productoAlmacenado[] @return;
        
        public listarPorAlmacenResponse() {
        }
        
        public listarPorAlmacenResponse(SoftPubWA.ServicioWeb.productoAlmacenado[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarPorNombre", WrapperNamespace="http://services.comerziasoft.pucp.edu.pe", IsWrapped=true)]
    public partial class buscarPorNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.comerziasoft.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreProd;
        
        public buscarPorNombreRequest() {
        }
        
        public buscarPorNombreRequest(string nombreProd) {
            this.nombreProd = nombreProd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarPorNombreResponse", WrapperNamespace="http://services.comerziasoft.pucp.edu.pe", IsWrapped=true)]
    public partial class buscarPorNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.comerziasoft.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPubWA.ServicioWeb.producto[] @return;
        
        public buscarPorNombreResponse() {
        }
        
        public buscarPorNombreResponse(SoftPubWA.ServicioWeb.producto[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorId", WrapperNamespace="http://services.comerziasoft.pucp.edu.pe", IsWrapped=true)]
    public partial class obtenerPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.comerziasoft.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id;
        
        public obtenerPorIdRequest() {
        }
        
        public obtenerPorIdRequest(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdResponse", WrapperNamespace="http://services.comerziasoft.pucp.edu.pe", IsWrapped=true)]
    public partial class obtenerPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.comerziasoft.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPubWA.ServicioWeb.almacen @return;
        
        public obtenerPorIdResponse() {
        }
        
        public obtenerPorIdResponse(SoftPubWA.ServicioWeb.almacen @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AlmacenWSChannel : SoftPubWA.ServicioWeb.AlmacenWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlmacenWSClient : System.ServiceModel.ClientBase<SoftPubWA.ServicioWeb.AlmacenWS>, SoftPubWA.ServicioWeb.AlmacenWS {
        
        public AlmacenWSClient() {
        }
        
        public AlmacenWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlmacenWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlmacenWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlmacenWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPubWA.ServicioWeb.insertarProductoAlmacenadoResponse SoftPubWA.ServicioWeb.AlmacenWS.insertarProductoAlmacenado(SoftPubWA.ServicioWeb.insertarProductoAlmacenadoRequest request) {
            return base.Channel.insertarProductoAlmacenado(request);
        }
        
        public int insertarProductoAlmacenado(int idAlmacen, System.DateTime fechaAlmacenado, int stock, int idProd) {
            SoftPubWA.ServicioWeb.insertarProductoAlmacenadoRequest inValue = new SoftPubWA.ServicioWeb.insertarProductoAlmacenadoRequest();
            inValue.idAlmacen = idAlmacen;
            inValue.fechaAlmacenado = fechaAlmacenado;
            inValue.stock = stock;
            inValue.idProd = idProd;
            SoftPubWA.ServicioWeb.insertarProductoAlmacenadoResponse retVal = ((SoftPubWA.ServicioWeb.AlmacenWS)(this)).insertarProductoAlmacenado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPubWA.ServicioWeb.insertarProductoAlmacenadoResponse> SoftPubWA.ServicioWeb.AlmacenWS.insertarProductoAlmacenadoAsync(SoftPubWA.ServicioWeb.insertarProductoAlmacenadoRequest request) {
            return base.Channel.insertarProductoAlmacenadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPubWA.ServicioWeb.insertarProductoAlmacenadoResponse> insertarProductoAlmacenadoAsync(int idAlmacen, System.DateTime fechaAlmacenado, int stock, int idProd) {
            SoftPubWA.ServicioWeb.insertarProductoAlmacenadoRequest inValue = new SoftPubWA.ServicioWeb.insertarProductoAlmacenadoRequest();
            inValue.idAlmacen = idAlmacen;
            inValue.fechaAlmacenado = fechaAlmacenado;
            inValue.stock = stock;
            inValue.idProd = idProd;
            return ((SoftPubWA.ServicioWeb.AlmacenWS)(this)).insertarProductoAlmacenadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPubWA.ServicioWeb.listarAlmacenesResponse SoftPubWA.ServicioWeb.AlmacenWS.listarAlmacenes(SoftPubWA.ServicioWeb.listarAlmacenesRequest request) {
            return base.Channel.listarAlmacenes(request);
        }
        
        public SoftPubWA.ServicioWeb.almacen[] listarAlmacenes() {
            SoftPubWA.ServicioWeb.listarAlmacenesRequest inValue = new SoftPubWA.ServicioWeb.listarAlmacenesRequest();
            SoftPubWA.ServicioWeb.listarAlmacenesResponse retVal = ((SoftPubWA.ServicioWeb.AlmacenWS)(this)).listarAlmacenes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPubWA.ServicioWeb.listarAlmacenesResponse> SoftPubWA.ServicioWeb.AlmacenWS.listarAlmacenesAsync(SoftPubWA.ServicioWeb.listarAlmacenesRequest request) {
            return base.Channel.listarAlmacenesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPubWA.ServicioWeb.listarAlmacenesResponse> listarAlmacenesAsync() {
            SoftPubWA.ServicioWeb.listarAlmacenesRequest inValue = new SoftPubWA.ServicioWeb.listarAlmacenesRequest();
            return ((SoftPubWA.ServicioWeb.AlmacenWS)(this)).listarAlmacenesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPubWA.ServicioWeb.buscarProductoPorIdResponse SoftPubWA.ServicioWeb.AlmacenWS.buscarProductoPorId(SoftPubWA.ServicioWeb.buscarProductoPorIdRequest request) {
            return base.Channel.buscarProductoPorId(request);
        }
        
        public SoftPubWA.ServicioWeb.producto buscarProductoPorId(int idProd) {
            SoftPubWA.ServicioWeb.buscarProductoPorIdRequest inValue = new SoftPubWA.ServicioWeb.buscarProductoPorIdRequest();
            inValue.idProd = idProd;
            SoftPubWA.ServicioWeb.buscarProductoPorIdResponse retVal = ((SoftPubWA.ServicioWeb.AlmacenWS)(this)).buscarProductoPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPubWA.ServicioWeb.buscarProductoPorIdResponse> SoftPubWA.ServicioWeb.AlmacenWS.buscarProductoPorIdAsync(SoftPubWA.ServicioWeb.buscarProductoPorIdRequest request) {
            return base.Channel.buscarProductoPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPubWA.ServicioWeb.buscarProductoPorIdResponse> buscarProductoPorIdAsync(int idProd) {
            SoftPubWA.ServicioWeb.buscarProductoPorIdRequest inValue = new SoftPubWA.ServicioWeb.buscarProductoPorIdRequest();
            inValue.idProd = idProd;
            return ((SoftPubWA.ServicioWeb.AlmacenWS)(this)).buscarProductoPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPubWA.ServicioWeb.listarPorAlmacenResponse SoftPubWA.ServicioWeb.AlmacenWS.listarPorAlmacen(SoftPubWA.ServicioWeb.listarPorAlmacenRequest request) {
            return base.Channel.listarPorAlmacen(request);
        }
        
        public SoftPubWA.ServicioWeb.productoAlmacenado[] listarPorAlmacen(string idAlmacen) {
            SoftPubWA.ServicioWeb.listarPorAlmacenRequest inValue = new SoftPubWA.ServicioWeb.listarPorAlmacenRequest();
            inValue.idAlmacen = idAlmacen;
            SoftPubWA.ServicioWeb.listarPorAlmacenResponse retVal = ((SoftPubWA.ServicioWeb.AlmacenWS)(this)).listarPorAlmacen(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPubWA.ServicioWeb.listarPorAlmacenResponse> SoftPubWA.ServicioWeb.AlmacenWS.listarPorAlmacenAsync(SoftPubWA.ServicioWeb.listarPorAlmacenRequest request) {
            return base.Channel.listarPorAlmacenAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPubWA.ServicioWeb.listarPorAlmacenResponse> listarPorAlmacenAsync(string idAlmacen) {
            SoftPubWA.ServicioWeb.listarPorAlmacenRequest inValue = new SoftPubWA.ServicioWeb.listarPorAlmacenRequest();
            inValue.idAlmacen = idAlmacen;
            return ((SoftPubWA.ServicioWeb.AlmacenWS)(this)).listarPorAlmacenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPubWA.ServicioWeb.buscarPorNombreResponse SoftPubWA.ServicioWeb.AlmacenWS.buscarPorNombre(SoftPubWA.ServicioWeb.buscarPorNombreRequest request) {
            return base.Channel.buscarPorNombre(request);
        }
        
        public SoftPubWA.ServicioWeb.producto[] buscarPorNombre(string nombreProd) {
            SoftPubWA.ServicioWeb.buscarPorNombreRequest inValue = new SoftPubWA.ServicioWeb.buscarPorNombreRequest();
            inValue.nombreProd = nombreProd;
            SoftPubWA.ServicioWeb.buscarPorNombreResponse retVal = ((SoftPubWA.ServicioWeb.AlmacenWS)(this)).buscarPorNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPubWA.ServicioWeb.buscarPorNombreResponse> SoftPubWA.ServicioWeb.AlmacenWS.buscarPorNombreAsync(SoftPubWA.ServicioWeb.buscarPorNombreRequest request) {
            return base.Channel.buscarPorNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPubWA.ServicioWeb.buscarPorNombreResponse> buscarPorNombreAsync(string nombreProd) {
            SoftPubWA.ServicioWeb.buscarPorNombreRequest inValue = new SoftPubWA.ServicioWeb.buscarPorNombreRequest();
            inValue.nombreProd = nombreProd;
            return ((SoftPubWA.ServicioWeb.AlmacenWS)(this)).buscarPorNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPubWA.ServicioWeb.obtenerPorIdResponse SoftPubWA.ServicioWeb.AlmacenWS.obtenerPorId(SoftPubWA.ServicioWeb.obtenerPorIdRequest request) {
            return base.Channel.obtenerPorId(request);
        }
        
        public SoftPubWA.ServicioWeb.almacen obtenerPorId(string id) {
            SoftPubWA.ServicioWeb.obtenerPorIdRequest inValue = new SoftPubWA.ServicioWeb.obtenerPorIdRequest();
            inValue.id = id;
            SoftPubWA.ServicioWeb.obtenerPorIdResponse retVal = ((SoftPubWA.ServicioWeb.AlmacenWS)(this)).obtenerPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPubWA.ServicioWeb.obtenerPorIdResponse> SoftPubWA.ServicioWeb.AlmacenWS.obtenerPorIdAsync(SoftPubWA.ServicioWeb.obtenerPorIdRequest request) {
            return base.Channel.obtenerPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPubWA.ServicioWeb.obtenerPorIdResponse> obtenerPorIdAsync(string id) {
            SoftPubWA.ServicioWeb.obtenerPorIdRequest inValue = new SoftPubWA.ServicioWeb.obtenerPorIdRequest();
            inValue.id = id;
            return ((SoftPubWA.ServicioWeb.AlmacenWS)(this)).obtenerPorIdAsync(inValue);
        }
    }
}
